trigger:
- master

pool:
  name: 'Default'  # Your self-hosted agent pool

steps:
# Install Java 17 on the agent (if not already installed)
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17.x'  # Use Java 17
    jdkArchitecture: 'x64'

# Maven build step
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'  # Reference JDK 17
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
