trigger:
- master

pool:
  name: 'Default'  # Use the specified self-hosted agent pool

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'   # Java 17 is already installed, specify it here
    jdkArchitectureOption: 'x64'  # Architecture should match your installed Java
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
